### ISSUE TITLE
Logo for agala

### ISSUE THREAD

**Issue by reallinfo** [agalaframework/agala#21]
Hello! I am a graphic designer. I want to contribute to agala. Do you want me to design a logo for the agala? Actually, I have an idea. Do you want to see this?

**Comment by Virviil** [comment]
@reallinfo I hope that you can make Pull Request with new logo, that will be discussed by the community

**Comment by reallinfo** [comment]
Okay,It was designed from the initial letter and function of the project.  i will wait for a feedback.

![agala](https://user-images.githubusercontent.com/36298335/40659610-69864cce-6357-11e8-93b0-89643973fc67.jpg)

![agala2](https://user-images.githubusercontent.com/36298335/40660947-2d0e068e-635b-11e8-9ae2-dc169f97f223.jpg)

**Comment by Virviil** [comment]
Thank you, great!

This is current Agala logo. So we can ask the community which one is better
![agala svg](https://user-images.githubusercontent.com/3989623/40711231-4e69e8cc-6403-11e8-9bb2-caa8a6864d8c.png)

**Comment by sofakingworld** [comment]
I liked this one 
![image](https://user-images.githubusercontent.com/15660128/40713067-e005d5bc-6407-11e8-9393-99a7d2c93cc4.png)

**Comment by Virviil** [comment]
@reallinfo 
It seems that this one is the best.
![image](https://user-images.githubusercontent.com/3989623/40980912-460f2604-68e2-11e8-8d77-f8ee3750d6e6.png)

What do you think about the same colors as in Elixir logo - a bit another purple? May be it will be better?
![image](https://user-images.githubusercontent.com/3989623/40980999-8a3426cc-68e2-11e8-8ef7-f32686843120.png)

In all cases, can you please provide high resolution PNG and SVG images to include in this repository in next Agala version?

**Comment by reallinfo** [comment]
![agala](https://user-images.githubusercontent.com/36298335/41005020-71e7e21a-6924-11e8-994f-2ebb61d34762.jpg)

How is this? If you like it, i will send all files.

**Comment by Virviil** [comment]
May be a bit more curve top line for "bubble", as in 
![image](https://user-images.githubusercontent.com/3989623/41032200-5bcd9c2e-698b-11e8-96cc-07153e2ebd30.png)
this logo?

And gradient - may be also from left to right, not 3-colors?

I think, you can argue if you think that something is better - I'm not a designer, so you probably know better

**Comment by reallinfo** [comment]
I think you are right. I've added a few color variations.  which of these do you like?
![agala](https://user-images.githubusercontent.com/36298335/41043993-dcb01bc4-69ad-11e8-9354-b77b734e79e0.jpg)

**Comment by dom4mod** [comment]
And one more
<img width="144" alt="screen shot 2018-06-07 at 11 51 54" src="https://user-images.githubusercontent.com/40018924/41083170-f28487b8-6a49-11e8-80a4-e02542f57320.png">

**Comment by sofakingworld** [comment]
@dom4mod 
this logo associates with  
![image](https://user-images.githubusercontent.com/15660128/41086758-a6c24172-6a43-11e8-80b3-6c22f13b542c.png)

**Comment by dom4mod** [comment]
<img width="213" alt="screen shot 2018-06-07 at 14 27 23" src="https://user-images.githubusercontent.com/40018924/41091033-1540a4ac-6a5f-11e8-95a4-65bf936d30f4.png">

**Comment by dom4mod** [comment]
<img width="576" alt="screen shot 2018-06-07 at 14 32 43" src="https://user-images.githubusercontent.com/40018924/41091308-aca7f9bc-6a5f-11e8-98b5-f35e3d0eca12.png">

**Comment by Virviil** [comment]
@reallinfo I hope that single color one is the best (second from left). What do you think about concept to add differentiation to agala_vk, agala_whatsapp, agala_fb and so on?

**Comment by reallinfo** [comment]
if you want, we can try these versions too.

**Comment by Virviil** [comment]
@reallinfo Can you please provide HQ png and SVG 
![screen shot 2018-06-11 at 10 54 03](https://user-images.githubusercontent.com/3989623/41219034-ccbce7ae-6d65-11e8-9ddb-6a51ee8bd808.png)

And may be try to create specific to vk, tg, WhatsApp, email and so on

**Comment by reallinfo** [comment]
I sent a pr. 

https://github.com/agalaframework/agala/pull/24

I added all files and logotype. I hope you like it. If you have any problems, you can write to me.

**Comment by Virviil** [comment]
Seems to be done
