### ISSUE TITLE
suppress timeout error

### ISSUE THREAD

**Issue by d4rk5eed** [agalaframework/agala#4]
hi guys
how to suppress _[error] %HTTPoison.Error{id: nil, reason: :timeout}_ message in log?

**Comment by Virviil** [comment]
I can move this error in :info layer, so you will suppress it using level :warning or :error.

Just want to know, why current state is not relevant for you?

**Comment by d4rk5eed** [comment]
> Just want to know, why current state is not relevant for you?

1. Since I understand long polling, it is not the error but side effect. No need to handle it as error
2. It clutters tailing of log-file
3. Last but not least, 1 second timeout generates 86400 strings per 24-hour and 158Mb of logs per month it goes critical on amazon nano instance

BTW what is optimal timeout value?

**Comment by Virviil** [comment]
> BTW what is optimal timeout value?

I think 5 second is enough. In all cases poller will make endless polling, so actually this thing does not influence the situation much.

**Comment by Virviil** [comment]
Try to fetch deps directly from develop branch in this repo, if all works - i'll add some more enchantments and push new version to hex.

**Comment by d4rk5eed** [comment]
Now issue seems to be in info log

**Comment by Virviil** [comment]
Updated to v1.0.3 release.
Please change your deps, because `b:develop` may be unstable.
